name: WeRead to Notion Sync

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug Environment
        run: |
          echo "WR_SKEY exists: ${{ secrets.WR_SKEY != '' }}"
          echo "WR_VID exists: ${{ secrets.WR_VID != '' }}"
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - run: pip install requests notion-client
      
      - run: python sync_weread_to_notion.py
        env:
          WR_SKEY: ${{ secrets.WR_SKEY }}
          WR_VID: ${{ secrets.WR_VID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
