name: Sync WeRead to Notion

on:
  schedule:
    - cron: '0 19 * * *'  # 每天UTC时间19:00（北京时间第二天3:00）运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests notion-client
    
    - name: Run sync script
      env:
        WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: python sync_weread_to_notion.py
